name: "Detect if build or deploy is necessarry from commit message"

description: "GitHub Action that analyzes commit message to determine if build or deploy is necessary"

inputs:
  commit_msg:
    description: "commit_msg setting: -- or ' ' defaults to: 'git log --format=%B -n 1 HEAD'"
    default: "--"
  keywords:
    description: "Keywords, space seperated string to match word, to skip build, for example skip-ci, skip-build"
    default: "skip-ci skip-build"
  strictness:
    description: "string, value can be low, moderate or high"
    default: low
  detect_type:
    description: "detection type: build or deploy"
    default: build
  directory:
    description: "directory where to look for commit message, if commit message not specified"
    default: "."

outputs:
  build_necessary:
    description: "Outputs to check if build is necessary, true or false"
    value: ${{ steps.build_commit_detect.outputs.build_necessary }}

runs:
  using: composite
  steps:
    - name: "Detect keyword in commit message"
      id: build_commit_detect
      run: |
        "${{ github.action_path }}/main.sh" "${{ inputs.commit_msg || ' ' }}" "${{ inputs.keywords || 'skip-ci skip-build' }}" "${{ inputs.detect_type || 'build' }}" "${{ inputs.directory || '.' }}"
      shell: bash
      env:
        BUID_DEPLOY_DETECTOR_STRICTNESS: ${{ inputs.strictness || 'low' }}
