name: 'Detect if build is necessarry in commit message'

description: GitHub Action that analyzes commit messages to determine if a build is necessary.

inputs:
  commit_msg:
    description: "commit_msg setting: -- or ' ' defaults to: 'git log --format=%B -n 1 HEAD'"
    default: "--"
  keywords:
    description: Keywords, space seperated string to match word, to skip build
    default: "skip-ci skip-build"
  strictness:
    description: string, value can be less or high
    default: less

outputs:
  build_necessarry:
    description: outputs to check if build is necessary, true or false
    value: ${{ steps.build_commit_detect.outputs.build_necessarry }}

runs:
  using: "composite"
  steps:
    - name: Detect keywords in commit message
      id: build_commit_detect
      run: |
        "${{ github.action_path }}/main.sh" "${{ inputs.commit_msg || ' ' }}" "${{ inputs.keywords || 'skip-ci skip-build' }}"
      shell: bash
      env:
        BUILD_COMMIT_DETECTOR_STRICTNESS: ${{ inputs.strictness || 'less' }}
